resources:
  repositories:
  # - repository: MyGitHubRepo0
  #   type: github
  #   endpoint: alexpisquared
  #   name: alexpisquared/AAV.Shared
  # - repository: MyGitHubRepo1
  #   type: github
  #   endpoint: alexpisquared
  #   name: alexpisquared/CI
  - repository: MyGitHubRepo2
    type: github
    endpoint: alexpisquared
    name: alexpisquared/CI-Reimagined-Invention

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/CI.Azure.CDCI*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- checkout: self
# - checkout: MyGitHubRepo0
# - checkout: MyGitHubRepo1
- checkout: MyGitHubRepo2
- script: dir $(Build.SourcesDirectory)

#Was Commented out:Removing, since not in CI-RI:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'                   #27 72s
    installationPath: $(Agent.ToolsDirectory)/dotnet  # new in Sep 2022
    includePreviewVersions: true                      # new in Sep 2022

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    # projects: '**\*.csproj'
    projects: |
      **\WindowsFormsLib.csproj
      **\SpeechSynthLib.csproj
    feedsToUse: 'select'
    verbosityRestore: 'Quiet'        #12 24s

# - task: MSBuild@1    
#   inputs:
#     solution: '**/CI.DPL.sln'
##[error]C:\hostedtoolcache\windows\dotnet\sdk\5.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): Error NETSDK1004: Assets file 'D:\a\1\s\AAV.Shared\Src\Net6.0\AAV.WPF\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.

## ++ 2021-07-09: fixing  error NETSDK1004: Assets file project.assets.json not found.
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
## ++ 2021-07-09: fixing  error NETSDK1004: Assets file project.assets.json not found. 200+s

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# - task: CopyFiles@2
#   inputs:
#     # SourceFolder: 'Src\\CI\\CI.DataSmarts\\bin\\Release'
#     SourceFolder: 'Src\\Net6.0\\WindowsFormsLib\\bin\\Release'
#     Contents: '**'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
#     CleanTargetFolder: true
#     OverWrite: true
#     retryCount: '10'
    
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'
