global using System;
global using System.Data;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
//obal using System.Text.Json; //tu: new and very performant Json lib (Dec 2021)
global using System.Runtime.CompilerServices;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Input;
global using System.Windows.Markup;
global using System.Windows.Threading;
global using CI.Standard.Lib.Base;
global using CI.Standard.Lib.Helpers;
global using LogMonitorConsoleApp;
global using Microsoft.Extensions.Logging;
global using StandardContracts.Lib;
