global using System;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using System.Linq;
global using System.Windows;
global using System.Windows.Input;
global using GenderApiLib;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using NameOrigin.Code1stModelGen;
global using static System.Diagnostics.Trace;
